language: csharp
solution: WebApplicationCI.sln
install:
  - nuget restore WebApplicationCI.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release WebApplicationCI.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./UnitTestProjectCI/bin/Release/UnitTestProjectCI.dll
notifications:
    slack: s88972231:oprmIbt3eugKHPQTbMpYFuHY